wandb_version: 1

dataset:
  desc: null
  value: twitter15
type:
  desc: null
  value: PoincareBall
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693306613.079858
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      2:
      - 1
      - 5
      - 53
      - 55
      - 76
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.15.5
      8:
      - 5
